### ISSUE TITLE
Possible memory leak with quadEM

### ISSUE THREAD

**Issue by JeremyWykes** [epics-modules/quadEM#23]
Hi Mark
We have encountered a problem when using the tetrAMM with the scan record, and varying AveragingTime through the scan by running the scan in table mode and having averagingTime one of the positioners. When running an xafs-like scan with constant count time through the pre-edge and edge, and then increasing count time through the xafs region, we see relatively constant memory usage whilst the count time is constant, then as soon as we start increasing averagingTime memory usage increases until the host IOC crashes. If we use constant count time, we can run for days without issue.

Our controls engineer Ben has done some digging:

> Steps to repeat; 
> I made a scan record with increasing averagingTime, like you might do for an XAFS. Code attached. I observe on htop the memory going up until crash.
> 
> maxMemory setting: I tried adding a maxMemory to drvQuadEM class constructor, but it still goes over this limit.
> 
> I added a "pNDArrayPool->emptyFreeList();" into "drvQuadEM::ddoDataCallbacks:", and you can observe the reported "PoolUsedMem" is now very low, like 10Meg out of 512Meg, but htop still reports increasing mem over max.
> 
> Looking at NDArrayPool.cpp there is malloc(), "new", and "delete" used for memory, but not "free()", so i tried to add "free(freeArray->pData);" to "NDArrayPool::emptyFreeList()", but my trials result in either crashing or still the memory goes up.
> 
> We are using:
> quadem 9-3
> adCore 3-11

```
"""
test increasing sample times from tetramm,
  like you might do for xafs
"""
from epics import caget, caput

from epics.devices import Scan

scan_mjr = "MEX1SSCAN01"
scan_mnr = "scan1"
scan_name = f"{scan_mjr}:{scan_mnr}"

save_dir = "/tmp"
base_name = "MEX1_" # filename prefix


detector_PVs = ["MEX1HOST12:USED_RAM_MONITOR"]
positioner_PV = "MEX1BPM02DAQ01:AveragingTime"
start = 0.05
end = 10
step = 0.01
positioner_delay = 0.3 # [s]

# setup saving file/dir
caput(f"{scan_mjr}:saveData_subDir", save_dir)
caput(f"{scan_mjr}:saveData_baseName", base_name)
scan1 = Scan(scan_name)

# abort anything running;
caput(f"{scan_mjr}:AbortScans.PROC",1)

# clear out
scan1.reset()

# trigger (if used)
scan1.add_trigger("MEX1BPM02DAQ01:Acquire")

for detector_PV in detector_PVs:
    scan1.add_detector(detector_PV)

scan1.positioner_delay(positioner_delay) # [s]

#add_positioner(self, drive, readback=None,
#                       start=None, stop=None, step=None,
#                       center=None, width=None,
#                       mode='linear', absolute=True, array=None):
scan1.add_positioner(positioner_PV,start=start,stop=end,step=step)

# run it
scan1.run()
```

**Comment by MarkRivers** [comment]
Since areaDetector drivers with much larger NDArrays and faster frame rates don’t have this issue I don’t think it can be a problem with NDArrayPool.

Are you using any plugins that are not part of ADCore?

Please attach screen shots of QECommonPlugins.adl and quadEM.adl when running in the mode that causes the issue. Also attach a screen shot of htop.

What is the rate of memory usage increase each time you run that scan?  How many times do you need to run the scan before the memory growth is apparent?

**Comment by MarkRivers** [comment]
What OS is the IOC running on?

What versions of base, asyn, and sscan?

**Comment by MarkRivers** [comment]
I have reproduced the problem.  I also find that processing the EmptyFreeList record is not properly freeing the memory.  This is puzzling because I just tested with the ADSimDetector and it is working fine for that.  I need to dig into this to understand why emptying the free list is not working with quadEM.

**Comment by MarkRivers** [comment]
I found and fixed the problem that processing the EmptyFreeList record for the quadEM driver was not working.  The problem was that drvQuadEM::writeInt32() was not calling the base class asynNDDriver::writeInt32() method for parameters belonging to the base class.

The memory growth that was happening is because as the averaging time is increased the driver creates NDArrays of increasing size.  This is a worst-case for the freelist pool system because it means none of the existing NDArrays in the pool are large enough, so it is constantly creating new, slightly larger NDArrays.

However, now that EmptyFreeList is working it is easy to prevent the memory growth you were seeing.  You just need to arrange for the EmptyFreeList record to be processed periodically.  One way would be to just set its SCAN field to "10 second".  Another way, which I tested, was to add EmptyFreeList as the second positioner to your scan record, with a start and end value of 1.  That way each time the averaging time is increased it will empty the free list. 

I also modified quadEM.adl (and other OPI versions) to include ADBuffers.adl.  This is the new screen.

![image](https://user-images.githubusercontent.com/6115534/173925311-669bcbf8-ab3d-4e6b-ab66-05ece63ab36e.png)

Now you can see the buffer memory and manually empty the list.

I have pushed these changes to the master branch.

**Comment by JeremyWykes** [comment]
I can confirm using EmptyList as a positioner in a scan keeps pool used memory to a low value, and total IOC memory grows close to the theoretical value you would expect from the NDArrays increasing in size as count time is increased. Furthermore, when repeating that same increasing count time scan I can confirm that total memory used by the IOC does not change significantly from the value achieved at the end of the previous scan.
